#!/bin/bash -x

[ x$1 = xSKIP ] && exit 77

base=`basename $1`
srcdir=`dirname $0` # HACK
out=${base%%gc}out

ref=$srcdir/${base%%gc}ref

[ -f ${base%%gc}ref ] && ref=${base%%gc}ref

make $out
# diff $out $ref
cat $out < $ref | diff -w -up - $ref --label $ref || exit 1
rm $out
